<?php
/**
 * AbabaServices
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ababa API
 *
 * A sample Ababa API this example demonstrate features of websites
 *
 * OpenAPI spec version: v1
 * Contact: info@zamsol.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * AbabaServices Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AbabaServices implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AbabaServices';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'transcription' => 'string',
        'analytics' => 'string',
        'insight' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'transcription' => 'transcription',
        'analytics' => 'analytics',
        'insight' => 'insight'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'transcription' => 'setTranscription',
        'analytics' => 'setAnalytics',
        'insight' => 'setInsight'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'transcription' => 'getTranscription',
        'analytics' => 'getAnalytics',
        'insight' => 'getInsight'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const TRANSCRIPTION_ACTIVE = 'active';
    const TRANSCRIPTION_INACTIVE = 'inactive';
    const ANALYTICS_INACTIVE = 'inactive';
    const ANALYTICS_ACTIVE = 'active';
    const INSIGHT_ACTIVE = 'active';
    const INSIGHT_INACTIVE = 'inactive';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getTranscriptionAllowableValues()
    {
        return [
            self::TRANSCRIPTION_ACTIVE,
            self::TRANSCRIPTION_INACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getAnalyticsAllowableValues()
    {
        return [
            self::ANALYTICS_INACTIVE,
            self::ANALYTICS_ACTIVE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getInsightAllowableValues()
    {
        return [
            self::INSIGHT_ACTIVE,
            self::INSIGHT_INACTIVE,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['transcription'] = isset($data['transcription']) ? $data['transcription'] : 'active';
        $this->container['analytics'] = isset($data['analytics']) ? $data['analytics'] : 'inactive';
        $this->container['insight'] = isset($data['insight']) ? $data['insight'] : 'active';
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("active", "inactive");
        if (!in_array($this->container['transcription'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'transcription', must be one of #{allowed_values}.";
        }

        $allowed_values = array("inactive", "active");
        if (!in_array($this->container['analytics'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'analytics', must be one of #{allowed_values}.";
        }

        $allowed_values = array("active", "inactive");
        if (!in_array($this->container['insight'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'insight', must be one of #{allowed_values}.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("active", "inactive");
        if (!in_array($this->container['transcription'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("inactive", "active");
        if (!in_array($this->container['analytics'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("active", "inactive");
        if (!in_array($this->container['insight'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets transcription
     * @return string
     */
    public function getTranscription()
    {
        return $this->container['transcription'];
    }

    /**
     * Sets transcription
     * @param string $transcription
     * @return $this
     */
    public function setTranscription($transcription)
    {
        $allowed_values = array('active', 'inactive');
        if (!in_array($transcription, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'transcription', must be one of 'active', 'inactive'");
        }
        $this->container['transcription'] = $transcription;

        return $this;
    }

    /**
     * Gets analytics
     * @return string
     */
    public function getAnalytics()
    {
        return $this->container['analytics'];
    }

    /**
     * Sets analytics
     * @param string $analytics
     * @return $this
     */
    public function setAnalytics($analytics)
    {
        $allowed_values = array('inactive', 'active');
        if (!in_array($analytics, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'analytics', must be one of 'inactive', 'active'");
        }
        $this->container['analytics'] = $analytics;

        return $this;
    }

    /**
     * Gets insight
     * @return string
     */
    public function getInsight()
    {
        return $this->container['insight'];
    }

    /**
     * Sets insight
     * @param string $insight
     * @return $this
     */
    public function setInsight($insight)
    {
        $allowed_values = array('active', 'inactive');
        if (!in_array($insight, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'insight', must be one of 'active', 'inactive'");
        }
        $this->container['insight'] = $insight;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


